config/routes.rb
Rails.application.routes.draw do

  resources :selected_modules, except: [:index]
  devise_for :users
  resources :course_modules

  root 'home#home'

  get 'response' , to: 'home#responsive'
  get 'contact' , to: 'home#contact'
  post 'request_contact' , to: 'home#request_contact'
  get 'my_modules' , to: 'course_modules#indexOwn'
  get 'selected_modules', to: 'course_modules#indexOwn'
  #get 'course_modules/new', to: 'course_modules#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/course_module.rb
class CourseModule < ApplicationRecord
  scope :by_user, -> (user) { joins("INNER JOIN selected_modules AS sm ON sm.course_module_id = course_modules.id").where([" sm.user_id = ?", user.id]) } #joins(:selected_modules).where([" selected_modules.user_id = ?", user.id]) }

  has_many :selected_modules, :dependent => :destroy

end

app/controllers/course_modules_controller.rb
class CourseModulesController < ApplicationController
  before_action :set_course_module, only: %i[ show edit update destroy   ]
  before_action :authenticate_user!

  # GET /course_modules or /course_modules.json
  def index
    @course_modules = CourseModule.all
  end

  # GET /course_modules/1 or /course_modules/1.json
  def show
  end

  def indexOwn
    @course_modules = CourseModule.by_user(current_user)
  end

  # GET /course_modules/new
  def new
    #@course_module = CourseModule.new
    redirect_to course_modules_url #redirect to the page of modules as the user should not be able to edit a module
  end

  # GET /course_modules/1/edit
  def edit
  end

  # POST /course_modules or /course_modules.json
  def create
    @course_module = CourseModule.new(course_module_params)

    respond_to do |format|
      if @course_module.save
        format.html { redirect_to @course_module, notice: "Course module was successfully created." }
        format.json { render :show, status: :created, location: @course_module }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_modules/1 or /course_modules/1.json
  def update
    respond_to do |format|
      if @course_module.update(course_module_params)
        format.html { redirect_to @course_module, notice: "Course module was successfully updated." }
        format.json { render :show, status: :ok, location: @course_module }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_modules/1 or /course_modules/1.json
  def destroy
    @course_module.destroy
    respond_to do |format|
      format.html { redirect_to course_modules_url, notice: "Course module was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_module
      @course_module = CourseModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_module_params
      params.require(:course_module).permit(:Title, :ModuleCode, :ModuleOverview, :ModuleLeader, :ModuleLeaderID, :Credits, :Year)
    end
end

app/helpers/course_modules_helper.rb
module CourseModulesHelper
end

app/views/course_modules/_form.html.haml
= form_for @course_module, :html => { :id => "editModForm", :class => 'edit_module_form'} do |f|
  - if @course_module.errors.any?
    #error_explanation
      %h2= "#{pluralize(@course_module.errors.count, "error")} prohibited this course_module from being saved:"
      %ul
        - @course_module.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label t('.title')
    = f.text_field :Title, size: 39, class: 'name formEntry'
  .field
    = f.label t('.module_code')
    = f.text_field :ModuleCode, size: 39, class: 'name formEntry'
  .field
    = f.label t('.module_overview')
    = f.text_field :ModuleOverview, size: 39, class: 'message formEntry'
  .field
    = f.label t('.module_leader')
    = f.text_field :ModuleLeader, size: 39, class: 'name formEntry'
  .field
    = f.label t('.module_leader_idm')
    = f.number_field :ModuleLeaderID, size: 39, class: 'name formEntry'
  .field
    = f.label t('.credits')
    = f.number_field :Credits, size: 39, class: 'name formEntry'
  .field
    = f.label t('.year')
    = f.number_field :Year, size: 39, class: 'name formEntry'
  .actions
    = f.submit t('.save_button'), class: 'btn'

app/views/course_modules/edit.html.haml
/-Page to edit a module
/-Not viewable to the user

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')

= render 'form'

= link_to t('.show_button'), @course_module, class: 'btn'
\|
= link_to t('.back_button'), course_modules_path, class: 'btn'

app/views/course_modules/index.html.haml
/-Page to view all modules

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')


%table
  %thead
    %tr
      %th= t('.module_title')
      %th= t('.module_code')
      %th= t('.module_overview')
      %th= t('.module_leader')
      %th= t('.credits')
      %th= t('.year')
      %th
      %th

  %tbody
    - @course_modules.each do |course_module|
      %tr
        %td= course_module.Title
        %td= course_module.ModuleCode
        %td= course_module.ModuleOverview
        %td= course_module.ModuleLeader
        %td= course_module.Credits
        %td= course_module.Year
        %td= link_to t('.show_button'), course_module #allow user to view details about the module
        %td= link_to t('.select_button'), new_selected_module_path(:module_id => course_module) #allow the user to select the module

%br

app/views/course_modules/indexOwn.html.haml
/-Page to display a user's selected modules

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')
  %p= t('.description')

%table
  /-Display the user's year and credits
  %div{class: "yearCreditsDisplay" }
    %h2 Your details
    %h3= t('.year') + ": " + (@current_user.year).to_s
    %h3= t('.credits') + ": " + (@current_user.credits).to_s

  %thead
    %tr
      %th= t('.module_title')
      %th= t('.module_code')
      %th= t('.module_overview')
      %th= t('.module_leader')
      %th= t('.credits')
      %th= t('.year')
      %th
      %th
      %th

  %tbody
    - @course_modules.each do |course_module|
      %tr
        %td= course_module.Title
        %td= course_module.ModuleCode
        %td= course_module.ModuleOverview
        %td= course_module.ModuleLeader
        %td= course_module.Credits
        %td= course_module.Year
        %td= link_to t('.show_button'), course_module #Allow the user to view details about that module
        %td= link_to t('.destroy_button'), selected_module_path(course_module.id), method: :delete, data: { confirm: 'Are you sure?' } #Allow the user to remove that module

%br

app/views/course_modules/new.html.haml
/-Page to edit course module
/-Not viewable to user

%h1= t('.title')

= render 'form'

= link_to t('.back_button'), course_modules_path

app/views/course_modules/show.html.haml
/-Module details page

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')
  %p= t('.description')

%p#notice= notice

.formWrapper
  %p
    %b= t('.title')
    = @course_module.Title
  %p
    %b= t('.module_code')
    = @course_module.ModuleCode
  %p
    %b= t('.module_overview')
    = @course_module.ModuleOverview
  %p
    %b= t('.module_leader')
    = @course_module.ModuleLeader
  %p
    %b= t('.credits')
    = @course_module.Credits
  %p
    %b= t('.year')
    = @course_module.Year

  = link_to t('.back_button'), course_modules_path, class:'btn'