config/routes.rb
Rails.application.routes.draw do

  resources :selected_modules, except: [:index]
  devise_for :users
  resources :course_modules

  root 'home#home'

  get 'response' , to: 'home#responsive'
  get 'contact' , to: 'home#contact'
  post 'request_contact' , to: 'home#request_contact'
  get 'my_modules' , to: 'course_modules#indexOwn'
  get 'selected_modules', to: 'course_modules#indexOwn'
  #get 'course_modules/new', to: 'course_modules#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def responsive

  end

  def contact

  end

  #validate the contact form
  def request_contact
    name = params[:name]
    email = params[:email]
    message = params[:message]
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.haml
/-Contact page

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1=t('.title')
  %p=t('.contact_us')




= form_tag request_contact_path, method: 'post', class: 'contact_form', id: 'contact_form' do
  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 39, class: 'name formEntry'
  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email'), size: 39, class: 'email formEntry'
  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 39, class: 'message formEntry'
  = submit_tag t('.submit')

app/views/home/home.html.haml
/-home page

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')
  %p= t('.welcome')

.homePageInstructions
  %p= t('.instruction1')
  %p= t('.instruction2')
  %p= t('.instruction3')
  %p= t('.instruction4')