config/routes.rb
Rails.application.routes.draw do

  resources :selected_modules, except: [:index]
  devise_for :users
  resources :course_modules

  root 'home#home'

  get 'response' , to: 'home#responsive'
  get 'contact' , to: 'home#contact'
  post 'request_contact' , to: 'home#request_contact'
  get 'my_modules' , to: 'course_modules#indexOwn'
  get 'selected_modules', to: 'course_modules#indexOwn'
  #get 'course_modules/new', to: 'course_modules#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/selected_module.rb
class SelectedModule < ApplicationRecord

  belongs_to :user
  belongs_to :course_module, class_name: "CourseModule"

  scope :by_user, -> (user) { where([" user_id = ?", user.id]) }

  validates :course_module_id, uniqueness: {scope: :user_id}

  validates :user_id, presence: true
  validates :course_module_id, presence: true

end

app/controllers/selected_modules_controller.rb
class SelectedModulesController < ApplicationController
  before_action :set_selected_module, only: %i[ show edit update  ]
  before_action :authenticate_user!

  # GET /selected_modules or /selected_modules.json
  def index
    @selected_modules = SelectedModule.all
  end

  # GET /selected_modules/1 or /selected_modules/1.json
  def show
  end

  # GET /selected_modules/new
  def new
    @selected_module = SelectedModule.new
    @selected_module.user = current_user

    # TODO: check if course_module is nil and return an error.
    @selected_module.course_module = CourseModule.find(params[:module_id])
    if @selected_module.course_module.nil?
      flash.alert = "Need course module id"
      redirect_to(my_modules_path, notice: "Need course module id")
      return
    end
  end

  # GET /selected_modules/1/edit
  def edit
  end

  # POST /selected_modules or /selected_modules.json
  def create
    @selected_module = SelectedModule.new(selected_module_params)

    #if the user already has 120 credits, then they should not be allowed to select another module
    if current_user.credits == 120
      respond_to do |format|
        format.html { redirect_to CourseModule, notice: "Cannot select another module - already have 120 credits." }
        format.json { render json: {
          message: "Cannot select another module - already have 120 credits."
        }, status: :created, location: @selected_module }
      end
      return
    end

    #if the year of the user does not match the year of the module, then they should not be allowed to select that module
    if current_user.year != @selected_module.course_module.Year
      respond_to do |format|
        format.html { redirect_to CourseModule, notice: "Cannot select this module - not in the correct year." }
        format.json { render json: {
          message: "Cannot select this module - not in the correct year."
        }, status: :created, location: @selected_module }
      end
      return
    end

    #if they don't already have 120 credits and they are in the right year, then continue with selecting the module
    respond_to do |format|
      if @selected_module.save
        format.html { redirect_to @selected_module, notice: "Selected module was successfully created." }
        format.json { render :show, status: :created, location: @selected_module }

        #add the module credits to the user's credits
        current_user.credits += @selected_module.course_module.Credits
        current_user.save
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @selected_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selected_modules/1 or /selected_modules/1.json
  def update
    respond_to do |format|
      if @selected_module.update(selected_module_params)
        format.html { redirect_to @selected_module, notice: "Selected module was successfully updated." }
        format.json { render :show, status: :ok, location: @selected_module }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @selected_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_modules/1 or /selected_modules/1.json
  def destroy

    @selected_module = SelectedModule.where(["course_module_id = ? AND user_id = ?", params[:id], current_user.id ]).first!

    @selected_module.destroy
    respond_to do |format|
      format.html { redirect_to my_modules_path, notice: "Selected module was successfully destroyed." }
      format.json { head :no_content }

      #subtract the module credits from the user's credits
      current_user.credits -= @selected_module.course_module.Credits
      current_user.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_module
      @selected_module = SelectedModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def selected_module_params
      params.require(:selected_module).permit(:id, :user_id, :course_module_id)
    end
end

app/helpers/selected_modules_helper.rb
module SelectedModulesHelper
end

app/views/selected_modules/_form.html.haml
.formWrapper
  = form_for @selected_module do |f|
    - if @selected_module.errors.any?
      #error_explanation
        %h2= "#{pluralize(@selected_module.errors.count, "error")} prohibited this selected_module from being saved:"
        %ul
          - @selected_module.errors.full_messages.each do |message|
            %li= message


    .field
      = f.hidden_field :id
    .field
      = f.hidden_field :user_id
    .field
      = f.hidden_field :course_module_id
    .field
      %b= t('.title')
      = @selected_module.course_module.Title
    .field
      %b= t('.module_code')
      = @selected_module.course_module.ModuleCode
    .field
      %b= t('.module_overview')
      = @selected_module.course_module.ModuleOverview
    .field
      %b= t('.module_leader')
      = @selected_module.course_module.ModuleLeader
    .field
      %b= t('.module_credits')
      = @selected_module.course_module.Credits
    .field
      %b= t('.module_year')
      = @selected_module.course_module.Year
    .actions
      = f.submit t('.confirm'), class:'btn'
    = link_to t('.cancel'), my_modules_path, class:'btn'

app/views/selected_modules/edit.html.haml
/-Edit selected module
/Not viewable to user

%h1=t('.title')

= render 'form'

= link_to t('.show'), @selected_module
\|
= link_to t('.back'), selected_modules_path

app/views/selected_modules/index.html.haml
/-Not viewable to user

%h1= t('.title')

%table
  %thead
    %tr
      %th= t('.id')
      %th= t('.id')
      %th= t('.course_module_id')
      %th
      %th
      %th

  %tbody
    - @selected_modules.each do |selected_module|
      %tr
        %td= selected_module.id
        %td= selected_module.user_id
        %td= selected_module.course_module_id
        %td= link_to t('.show'), selected_module
        %td= link_to  t('.edit'), edit_selected_module_path(selected_module)
        %td= link_to t('.destroy'), selected_module, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to t('.new_selected_module'), new_selected_module_path

app/views/selected_modules/new.html.haml
/-Confirmation page for when a user wants to select a module

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')
  %p= t('.description')

= render 'form'

app/views/selected_modules/show.html.haml
/-Success page for when the user selects a module

= render "shared/backgroundAnimation"

.jumbotron.text-center
  %h1= t('.title')

%div{class: "outside"}
  %div{class: "inside"}
    %h2= t('.success_message')

  %div{ class: "center" }
    = link_to 'Reload modules', my_modules_path, class:'btn'